import express from 'express'
import cors from 'cors'
import os from 'node:os'
import dgram from 'node:dgram'
import crypto from 'node:crypto'
import {execFile} from 'node:child_process'
import {promisify} from 'node:util'

const exec=promisify(execFile),app=express(),PORT=17855
app.use(cors({origin:true}));app.use(express.json({limit:'64kb'}))
function localNetwork(){const list=[];for(const [name,items] of Object.entries(os.networkInterfaces()))for(const x of items||[])if(x.family==='IPv4'&&!x.internal)list.push({interface:name,address:x.address,netmask:x.netmask,mac:x.mac});return list}
function prefix(mask){return mask.split('.').reduce((n,o)=>n+(Number(o).toString(2).match(/1/g)||[]).length,0)}
function ipNum(ip){return ip.split('.').reduce((n,o)=>(n*256)+Number(o),0)>>>0}
function numIp(n){return [24,16,8,0].map(s=>(n>>>s)&255).join('.')}
async function ping(ip){try{await exec(process.platform==='win32'?'ping':'ping',process.platform==='win32'?['-n','1','-w','180',ip]:['-c','1','-W','1',ip],{windowsHide:true});return true}catch{return false}}
async function arp(){try{const{stdout}=await exec(process.platform==='win32'?'arp':'arp',process.platform==='win32'?['-a']:['-an']);return stdout}catch{return ''}}
function parseArp(text){const out=[];for(const line of text.split(/\r?\n/)){const m=line.match(/(\d{1,3}(?:\.\d{1,3}){3})\s+([0-9a-f]{2}(?:[-:][0-9a-f]{2}){5})/i);if(m)out.push({ip:m[1],mac:m[2].replace(/-/g,':').toUpperCase()})}return out}
function wsDiscovery(){return new Promise(resolve=>{const socket=dgram.createSocket('udp4'),found=new Map(),action=`urn:uuid:${crypto.randomUUID()}`;const body=`<?xml version="1.0" encoding="UTF-8"?><e:Envelope xmlns:e="http://www.w3.org/2003/05/soap-envelope" xmlns:w="http://schemas.xmlsoap.org/ws/2004/08/addressing" xmlns:d="http://schemas.xmlsoap.org/ws/2005/04/discovery" xmlns:dn="http://www.onvif.org/ver10/network/wsdl"><e:Header><w:MessageID>${action}</w:MessageID><w:To>urn:schemas-xmlsoap-org:ws:2005:04:discovery</w:To><w:Action>http://schemas.xmlsoap.org/ws/2005/04/discovery/Probe</w:Action></e:Header><e:Body><d:Probe><d:Types>dn:NetworkVideoTransmitter</d:Types></d:Probe></e:Body></e:Envelope>`;const timer=setTimeout(()=>{try{socket.close()}catch{};resolve([...found.values()])},3000);socket.on('message',(msg,rinfo)=>{const xml=msg.toString();const xaddrs=[...xml.matchAll(/<[^>]*XAddrs[^>]*>([^<]+)</gi)].map(m=>m[1].trim()).flatMap(v=>v.split(/\s+/));const scopes=[...xml.matchAll(/<[^>]*Scopes[^>]*>([^<]+)</gi)].map(m=>m[1].trim()).join(' ');if(rinfo.address&&!found.has(rinfo.address))found.set(rinfo.address,{ip:rinfo.address,type:'IP Camera',protocol:'ONVIF',xaddrs,scopes})});socket.on('error',()=>{clearTimeout(timer);try{socket.close()}catch{};resolve([...found.values()])});socket.bind(()=>{try{socket.setBroadcast(true);socket.addMembership('239.255.255.250')}catch{};socket.send(Buffer.from(body),3702,'239.255.255.250')})})}
async function portOpen(ip,port){try{const ps=process.platform==='win32'?'powershell':'sh';const args=process.platform==='win32'?['-NoProfile','-Command',`$c=New-Object Net.Sockets.TcpClient;try{$c.Connect('${ip}',${port});'open'}catch{'closed'}finally{$c.Close()}`]:['-c',`(echo >/dev/tcp/${ip}/${port}) 2>/dev/null && echo open || echo closed`];const{stdout}=await exec(ps,args,{windowsHide:true,timeout:900});return String(stdout).includes('open')}catch{return false}}
function firstFree(subnet,used,count){const m=String(subnet).match(/^(\d+\.\d+\.\d+)\.\d+\/(\d+)$/);if(!m)throw Error('Only /24 CCTV subnet planning is supported currently');const base=m[1],usedSet=new Set(used),out=[];for(let i=2;i<=254&&out.length<count;i++){const ip=`${base}.${i}`;if(!usedSet.has(ip))out.push(ip)}return out}
function esc(v){return String(v).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&apos;')}
function wsse(user,pwd){const nonce=crypto.randomBytes(16),created=new Date().toISOString(),digest=crypto.createHash('sha1').update(Buffer.concat([nonce,Buffer.from(created),Buffer.from(pwd)])).digest('base64');return `<wsse:Security soap:mustUnderstand="1"><wsse:UsernameToken><wsse:Username>${esc(user)}</wsse:Username><wsse:Password Type="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-username-token-profile-1.0#PasswordDigest">${digest}</wsse:Password><wsse:Nonce EncodingType="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-soap-message-security-1.0#Base64Binary">${nonce.toString('base64')}</wsse:Nonce><wsu:Created>${created}</wsu:Created></wsse:UsernameToken></wsse:Security>`}
function setNetworkXml(user,pwd,ip,prefixLen){return `<?xml version="1.0" encoding="UTF-8"?><s:Envelope xmlns:s="http://www.w3.org/2003/05/soap-envelope" xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:t="http://www.onvif.org/ver10/schema" xmlns:tds="http://www.onvif.org/ver10/device/wsdl"><s:Header>${wsse(user,pwd)}</s:Header><s:Body><tds:SetNetworkInterfaces><tds:InterfaceToken>eth0</tds:InterfaceToken><tds:NetworkInterface><t:IPv4><t:Enabled>true</t:Enabled><t:Manual><t:PrefixedIPv4Address><t:Address>${esc(ip)}</t:Address><t:PrefixLength>${Number(prefixLen)}</t:PrefixLength></t:PrefixedIPv4Address></t:Manual><t:DHCP><t:Enabled>false</t:Enabled></t:DHCP></t:IPv4></tds:NetworkInterface></tds:SetNetworkInterfaces></s:Body></s:Envelope>`}
function soapRequest(url,xml){return new Promise((resolve,reject)=>{const u=new URL(url),mod=u.protocol==='https:'?require('node:https'):require('node:http');const req=mod.request({hostname:u.hostname,port:u.port||undefined,path:u.pathname||'/',method:'POST',headers:{'Content-Type':'application/soap+xml; charset=utf-8','Content-Length':Buffer.byteLength(xml)},rejectUnauthorized:false,timeout:6000},res=>{let b='';res.on('data',c=>b+=c);res.on('end',()=>res.statusCode>=200&&res.statusCode<300?resolve(b):reject(Error(`ONVIF HTTP ${res.statusCode}`)))});req.on('error',reject);req.on('timeout',()=>{req.destroy();reject(Error('ONVIF timeout'))});req.write(xml);req.end()})}
app.get('/api/status',(req,res)=>res.json({ok:true,agent:'Unique Market Network Agent',version:'0.3.0',interfaces:localNetwork()}))
app.get('/api/scan',async(req,res)=>{try{const nic=localNetwork().find(x=>x.address&&x.netmask);if(!nic)throw Error('No active IPv4 LAN interface found');const p=prefix(nic.netmask),mask=p===32?0xffffffff:(0xffffffff<<(32-p))>>>0,base=ipNum(nic.address)&mask,broadcast=(base|(~mask>>>0))>>>0,hostCount=Math.min(254,Math.max(0,broadcast-base-1)),start=base+1,devices=[];for(let i=0;i<hostCount;i+=32){const batch=[];for(let j=i;j<Math.min(i+32,hostCount);j++)batch.push(start+j);devices.push(...(await Promise.all(batch.map(n=>{const ip=numIp(n);return ping(ip).then(ok=>ok?{ip,status:'online',source:'icmp'}:null)}))).filter(Boolean))}const table=await arp(),arpRows=parseArp(table),onvif=await wsDiscovery(),omap=new Map(onvif.map(x=>[x.ip,x])),merged=devices.map(d=>{const a=arpRows.find(x=>x.ip===d.ip),c=omap.get(d.ip);return {...d,...(a?{mac:a.mac}:{}),...(c?{type:'IP Camera',protocol:'ONVIF',xaddrs:c.xaddrs,scopes:c.scopes}:{}),ports:{}}});for(const d of merged)for(const port of [80,443,554,8000,8080,37777])d.ports[port]=await portOpen(d.ip,port);res.json({ok:true,interface:nic,subnet:`${numIp(base)}/${p}`,devices:merged,onvif,onvifCount:onvif.length,arp:table,scannedAt:new Date().toISOString()})}catch(e){res.status(500).json({ok:false,error:e.message||'Network scan failed'})}})
app.get('/api/onvif-discovery',async(req,res)=>res.json({ok:true,devices:await wsDiscovery()}))
app.post('/api/ip-plan',async(req,res)=>{try{const{subnet,usedIps=[],count=1}=req.body||{},n=Math.min(256,Math.max(1,Number(count)||1)),ips=firstFree(subnet,usedIps,n);res.json({ok:true,count:n,ips,verifiedAgainstScan:false,note:'A fresh scan is required immediately before applying changes.'})}catch(e){res.status(400).json({ok:false,error:e.message})}})
app.post('/api/auto-camera-ip',async(req,res)=>{try{const{url,username,password,newIp,prefixLength=24,confirm}=req.body||{};if(confirm!==true)throw Error('Explicit confirmation is required');if(!url||!username||!password||!newIp)throw Error('ONVIF URL, username, password and target IP are required');if(!/^https?:\/\//i.test(url))throw Error('Only HTTP/HTTPS ONVIF endpoints are supported');const xml=setNetworkXml(username,password,newIp,prefixLength),body=await soapRequest(url,xml);res.json({ok:true,newIp,rebootNeeded:/RebootNeeded[^>]*>true/i.test(body),message:'ONVIF network configuration request accepted. Verify the camera at the new IP.'})}catch(e){res.status(400).json({ok:false,error:e.message})}})
app.listen(PORT,'127.0.0.1',()=>console.log(`Unique Market Network Agent listening on http://127.0.0.1:${PORT}`))
