import {useEffect,useState} from 'react'
import {supabase} from '../lib/supabase'

const categories=[
 ['cctv','📹 CCTV / Camera'],['computer','💻 Computer / Laptop'],['network','🌐 Networking / Internet'],['printer','🖨️ Printer / Scanner'],['access_control','🔐 Biometric / Access Control'],['vdp','🚪 Video Door Phone'],['tv','📺 TV / Display'],['dvr_nvr','💾 DVR / NVR / Storage'],['wifi_router','📡 Wi-Fi / Router'],['ups','🔌 Power / UPS'],['installation','🛠️ Installation / Configuration'],['amc','🔧 AMC / Maintenance'],['hardware','📦 Product / Hardware']
]

export default function AdminSettings({onBack}){
 const [saved,setSaved]=useState(false),[loading,setLoading]=useState(true),[message,setMessage]=useState(''),[settings,setSettings]=useState({maintenance:false,topology:false,notifications:true,upi_id:'',account_name:'',qr_image_url:'',is_enabled:true,max_radius_km:20,active_categories:categories.map(x=>x[0])})
 useEffect(()=>{(async()=>{const [{data:s},{data:access,error}]=await Promise.all([supabase.from('payment_settings').select('upi_id,account_name,qr_image_url,is_enabled').limit(1).maybeSingle(),supabase.from('service_access_settings').select('max_radius_km,active_categories').limit(1).maybeSingle()]);if(s)setSettings(x=>({...x,...s}));if(!error&&access)setSettings(x=>({...x,max_radius_km:Number(access.max_radius_km)||20,active_categories:Array.isArray(access.active_categories)&&access.active_categories.length?access.active_categories:categories.map(c=>c[0])}));setLoading(false)})()},[])
 function update(k,v){setSettings(s=>({...s,[k]:v}));setSaved(false);setMessage('')}
 function toggleCategory(id){setSettings(s=>({...s,active_categories:s.active_categories.includes(id)?s.active_categories.filter(x=>x!==id):[...s.active_categories,id]}));setSaved(false)}
 async function save(){setMessage('');setSaved(false);Object.entries(settings).filter(([k])=>['maintenance','topology','notifications'].includes(k)).forEach(([k,v])=>localStorage.setItem(`um_${k}`,String(v)));const {data:user}=await supabase.auth.getUser();const {data,error}=await supabase.from('payment_settings').select('id').limit(1).maybeSingle();if(!error){const payload={upi_id:settings.upi_id.trim()||null,account_name:settings.account_name.trim()||null,qr_image_url:settings.qr_image_url.trim()||null,is_enabled:settings.is_enabled,updated_by:user.user?.id||null,updated_at:new Date().toISOString()};const result=data?await supabase.from('payment_settings').update(payload).eq('id',data.id):await supabase.from('payment_settings').insert(payload);if(result.error){setMessage(result.error.message);return}}const {error:accessError}=await supabase.from('service_access_settings').update({max_radius_km:Math.max(1,Number(settings.max_radius_km)||20),active_categories:settings.active_categories,updated_at:new Date().toISOString()}).not('id','is',null);if(accessError){setMessage(accessError.message);return}setSaved(true);setMessage('Settings saved successfully')}
 return <section className='admin-panel'><div className='panel-heading'><div><span className='badge'>ADMIN • SETTINGS</span><h2>System Settings</h2><p>Control operational features, service access and the Unique Market payment account.</p></div><button className='secondary' onClick={onBack}>← Dashboard</button></div>{message&&<p className={saved?'muted':'error'}>{message}</p>}{loading?<p className='muted'>Loading settings…</p>:<><div className='admin-form'><label>Maintenance mode <input type='checkbox' checked={settings.maintenance} onChange={e=>update('maintenance',e.target.checked)}/></label><label>Visual Network Topology <input type='checkbox' checked={settings.topology} onChange={e=>update('topology',e.target.checked)}/></label><label>Admin notifications <input type='checkbox' checked={settings.notifications} onChange={e=>update('notifications',e.target.checked)}/></label></div><hr/><div><span className='badge'>SERVICE ACCESS</span><h3>Customer Service Access</h3><p className='muted'>Only enabled categories are shown to customers. The service radius is controlled here.</p><div className='admin-form'><label>Maximum service radius (km)<input type='number' min='1' max='200' step='0.1' value={settings.max_radius_km} onChange={e=>update('max_radius_km',e.target.value)}/></label><label>Service categories</label><div className='admin-actions'>{categories.map(([id,label])=><button type='button' key={id} className={settings.active_categories.includes(id)?'':'secondary'} onClick={()=>toggleCategory(id)}>{settings.active_categories.includes(id)?'✓ ':'○ '}{label}</button>)}</div></div></div><hr/><div><span className='badge'>PAYMENT • UPI / QR</span><h3>Customer UPI Account</h3><div className='admin-form'><label>UPI ID<input value={settings.upi_id||''} onChange={e=>update('upi_id',e.target.value)} placeholder='yourname@upi'/></label><label>Account / Business Name<input value={settings.account_name||''} onChange={e=>update('account_name',e.target.value)} placeholder='Unique Market'/></label><label>QR Image URL <input value={settings.qr_image_url||''} onChange={e=>update('qr_image_url',e.target.value)} placeholder='Optional hosted QR image URL'/></label><label>Enable customer UPI <input type='checkbox' checked={settings.is_enabled!==false} onChange={e=>update('is_enabled',e.target.checked)}/></label><div><button onClick={save}>Save Settings</button></div></div></div></>}</section>
}