import {useEffect,useState} from 'react'
import {supabase} from '../lib/supabase'
const stages=['open','assigned','in_progress','resolved','closed']
const labels={open:'New',assigned:'Assigned',in_progress:'In Progress',resolved:'Resolved',closed:'Closed'}
export default function AdminComplaintKanban({onBack}){const [items,setItems]=useState([]),[technicians,setTechnicians]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState('')
async function load(){setLoading(true);setError('');const [{data,error},{data:techs,error:te}] = await Promise.all([supabase.from('complaints').select('*').order('created_at',{ascending:false}).limit(300),supabase.from('profiles').select('id,full_name,phone').eq('role','technician').order('full_name')]);if(error)setError(error.message);else setItems(data||[]);if(te)setError(te.message);else setTechnicians(techs||[]);setLoading(false)}
useEffect(()=>{load()},[])
async function assign(id,technician_id){setError('');const patch={technician_id:technician_id||null,assigned_at:technician_id?new Date().toISOString():null,status:technician_id?'assigned':'open'};const {error}=await supabase.from('complaints').update(patch).eq('id',id);if(error)setError(error.message);else setItems(x=>x.map(c=>c.id===id?{...c,...patch}:c))}
async function move(id,status){const {error}=await supabase.from('complaints').update({status,updated_at:new Date().toISOString()}).eq('id',id);if(error)setError(error.message);else setItems(x=>x.map(c=>c.id===id?{...c,status}:c))}
function no(c){return c.complaint_no||c.ticket_no||'Complaint'}
return <section className="admin-panel"><div className="panel-heading"><div><span className="badge">ADMIN • LIVE</span><h2>Complaint Kanban</h2><p>Live complaints from Supabase with technician assignment.</p></div><button className="secondary" onClick={onBack}>← Dashboard</button></div>{error&&<p className="error">{error}</p>}<div className="admin-actions"><button className="secondary" onClick={load}>↻ Refresh</button></div>{loading?<p className="muted">Loading complaints…</p>:<div className="kanban">{stages.map(stage=><div className="kanban-column" key={stage}><h3>{labels[stage]} <small>{items.filter(c=>(c.status||'open')===stage).length}</small></h3>{items.filter(c=>(c.status||'open')===stage).map(c=><article className="kanban-card" key={c.id}><strong>{no(c)}</strong><p>{c.customer_name||'Customer'} {c.customer_phone?'• '+c.customer_phone:''}</p><p>{c.description||c.title||c.category||'No description'}</p><span>{c.priority||'Normal'}{c.technician_id?' • Technician assigned':''}</span><div style={{marginTop:8}}><select value={c.technician_id||''} onChange={e=>assign(c.id,e.target.value)}><option value="">Assign technician…</option>{technicians.map(t=><option key={t.id} value={t.id}>{t.full_name||t.phone||t.id}</option>)}</select></div><div className="kanban-actions">{stages.filter(s=>s!==stage).map(s=><button className="secondary" key={s} onClick={()=>move(c.id,s)}>{labels[s]}</button>)}</div></article>)}</div>)}</div>}</section>}
