import {useEffect,useState} from 'react'
import {supabase} from '../lib/supabase'
const stages=['new','assigned','in_progress','resolved','closed']
const labels={new:'New',assigned:'Assigned',in_progress:'In Progress',resolved:'Resolved',closed:'Closed'}
export default function AdminComplaintKanban({onBack}){const [items,setItems]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState('')
async function load(){setLoading(true);const {data,error}=await supabase.from('complaints').select('*').order('created_at',{ascending:false}).limit(300);if(error)setError(error.message);else setItems(data||[]);setLoading(false)}
useEffect(()=>{load()},[])
async function move(id,status){const {error}=await supabase.from('complaints').update({status}).eq('id',id);if(error)setError(error.message);else setItems(x=>x.map(c=>c.id===id?{...c,status}:c))}
return <section className="admin-panel"><div className="panel-heading"><div><span className="badge">ADMIN • LIVE</span><h2>Complaint Kanban</h2><p>Live complaint workflow from Supabase.</p></div><button className="secondary" onClick={onBack}>← Dashboard</button></div>{error&&<p className="error">{error}</p>}<div className="admin-actions"><button className="secondary" onClick={load}>↻ Refresh</button></div>{loading?<p className="muted">Loading complaints…</p>:<div className="kanban">{stages.map(stage=><div className="kanban-column" key={stage}><h3>{labels[stage]} <small>{items.filter(c=>(c.status||'new')===stage).length}</small></h3>{items.filter(c=>(c.status||'new')===stage).map(c=><article className="kanban-card" key={c.id}><strong>{c.ticket_no||c.title||c.category||'Complaint'}</strong><p>{c.description||'No description'}</p><span>{c.priority||'Normal'}{c.technician_id?' • Technician assigned':''}</span><div className="kanban-actions">{stages.filter(s=>s!==stage).map(s=><button className="secondary" key={s} onClick={()=>move(c.id,s)}>{labels[s]}</button>)}</div></article>)}</div>)}</div>}</section>}
