import React,{useEffect} from 'react'
const SITE='https://www.salesuniquemarket.com'
const PHONE='+918554887026'
const ADDRESS='Station Road, Hotel Rajdoot, Ichalkaranji, Maharashtra 416115, India'
export const pages={
'/cctv-camera-dealer-ichalkaranji':{title:'CCTV Camera Dealer in Ichalkaranji | Unique Market',heading:'CCTV Camera Dealer in Ichalkaranji',intro:'Unique Market is a local CCTV camera dealer in Ichalkaranji providing CCTV cameras, DVR, NVR, surveillance HDD, PoE networking and complete security solutions for homes, shops, offices, factories and commercial properties.',service:'CCTV Camera Dealer',keywords:'CCTV camera dealer Ichalkaranji, CCTV camera shop Ichalkaranji, CCTV cameras Ichalkaranji, security camera dealer Ichalkaranji',points:['Hikvision, CP Plus and Hi-Focus CCTV solutions','Indoor, outdoor, dome, bullet and IP cameras','DVR, NVR, surveillance HDD, PoE switch and networking products','Site survey, camera selection, installation and system configuration']},
'/cctv-installation-ichalkaranji':{title:'CCTV Installation in Ichalkaranji | Unique Market',heading:'Professional CCTV Installation in Ichalkaranji',intro:'Professional CCTV installation and configuration for residential, commercial and industrial locations across Ichalkaranji, with proper camera placement, cabling, networking and remote viewing setup.',service:'CCTV Installation',keywords:'CCTV installation Ichalkaranji, CCTV fitting Ichalkaranji, camera installation Ichalkaranji, CCTV installer Ichalkaranji',points:['Camera placement and coverage planning','DVR/NVR setup and remote mobile viewing configuration','Cat5e/Cat6 cabling, networking and PoE installation','Testing, commissioning and customer handover']},
'/cctv-service-ichalkaranji':{title:'CCTV Service & Repair in Ichalkaranji | Unique Market',heading:'CCTV Service & Repair in Ichalkaranji',intro:'Reliable CCTV service, repair, troubleshooting and maintenance for existing surveillance systems in Ichalkaranji. We support cameras, DVR/NVR, storage, networking and remote viewing issues.',service:'CCTV Service & Repair',keywords:'CCTV service Ichalkaranji, CCTV repair Ichalkaranji, CCTV maintenance Ichalkaranji, DVR repair Ichalkaranji',points:['Camera, DVR and NVR troubleshooting','HDD, recording and playback health checks','Remote viewing, network and mobile app troubleshooting','System health checks, cleaning and preventive maintenance']},
'/cctv-amc-ichalkaranji':{title:'CCTV AMC in Ichalkaranji | Unique Market',heading:'CCTV AMC & Maintenance in Ichalkaranji',intro:'CCTV Annual Maintenance Contract solutions to keep surveillance systems maintained, monitored and operational for homes, shops, offices, factories and businesses.',service:'CCTV AMC',keywords:'CCTV AMC Ichalkaranji, CCTV maintenance contract Ichalkaranji, CCTV annual maintenance Ichalkaranji',points:['Preventive CCTV system inspection','Camera, DVR/NVR and storage health checks','Cleaning and basic configuration support','Breakdown support and maintenance planning']},
'/computer-sales-service-ichalkaranji':{title:'Computer Sales & Service in Ichalkaranji | Unique Market',heading:'Computer Sales & Service in Ichalkaranji',intro:'Unique Market provides computer sales, desktop setup, Windows installation, driver support, troubleshooting, networking and IT support for homes, offices and businesses in Ichalkaranji.',service:'Computer Sales & Service',keywords:'computer shop Ichalkaranji, computer sales Ichalkaranji, computer service Ichalkaranji, desktop repair Ichalkaranji, laptop service Ichalkaranji, computer dealer Ichalkaranji',points:['Desktop, PC and computer system sales and setup','Windows installation, drivers and software support','Computer troubleshooting, upgrades and maintenance','Networking, printer, router and IT peripheral support']}}
const links=Object.keys(pages)
function setMeta(name,content){let m=document.querySelector(`meta[name="${name}"]`);if(!m){m=document.createElement('meta');m.name=name;document.head.appendChild(m)}m.content=content}
function setLink(rel,href){let l=document.querySelector(`link[rel="${rel}"]`);if(!l){l=document.createElement('link');l.rel=rel;document.head.appendChild(l)}l.href=href}
export default function LocalSeoPage(){
 const path=window.location.pathname.replace(/\/$/,'')||links[0],page=pages[path]||pages[links[0]]
 useEffect(()=>{
  document.title=page.title
  setMeta('description',page.intro+' Call Unique Market at +91 8554887026 or visit Station Road, Hotel Rajdoot, Ichalkaranji.')
  setMeta('keywords',page.keywords)
  setMeta('robots','index, follow, max-image-preview:large, max-snippet:-1, max-video-preview:-1')
  setLink('canonical',`${SITE}${path}`)
  const id='seo-localbusiness-schema';let s=document.getElementById(id);if(!s){s=document.createElement('script');s.id=id;s.type='application/ld+json';document.head.appendChild(s)}
  s.textContent=JSON.stringify({'@context':'https://schema.org','@type':'LocalBusiness','name':'Unique Market','description':page.intro,'url':`${SITE}${path}`,'telephone':PHONE,'address':{'@type':'PostalAddress','streetAddress':'Station Road, Hotel Rajdoot','addressLocality':'Ichalkaranji','addressRegion':'Maharashtra','postalCode':'416115','addressCountry':'IN'},'areaServed':['Ichalkaranji','Kolhapur','Sangli','Jaysingpur','Hatkanangale'],'serviceType':page.service,'sameAs':[SITE]})
 },[page,path])
 return <main className='seo-page'>
  <header className='seo-header'><a className='seo-brand' href='/'>UNIQUE MARKET</a><a className='seo-login' href='/login'>Customer / Technician Login</a></header>
  <section className='seo-hero'><span className='seo-badge'>ICHALKARANJI • CCTV • COMPUTER • IT SECURITY</span><h1>{page.heading}</h1><p>{page.intro}</p><div className='seo-actions'><a href={`tel:${PHONE}`}>Call +91 8554887026</a><a href={`https://wa.me/${PHONE.replace('+','')}`}>WhatsApp Us</a></div></section>
  <section className='seo-section'><h2>{page.service} in Ichalkaranji</h2><p>Unique Market provides practical CCTV, computer and IT solutions with product supply, installation, configuration, troubleshooting and after-sales support. We serve residential, commercial and industrial customers in Ichalkaranji and nearby areas.</p><div className='seo-grid'>{page.points.map(point=><article key={point}><strong>{point}</strong><p>Professional support focused on reliable products, correct installation and dependable after-sales service.</p></article>)}</div></section>
  <section className='seo-section'><h2>Why choose Unique Market?</h2><div className='seo-grid'><article><strong>Local Ichalkaranji support</strong><p>Based at Station Road, Hotel Rajdoot, Ichalkaranji.</p></article><article><strong>Complete CCTV solutions</strong><p>From camera selection and cabling to DVR/NVR configuration and remote viewing.</p></article><article><strong>Computer & networking support</strong><p>PC setup, Windows and driver support, routers, LAN, PoE and IT peripherals.</p></article><article><strong>Service & AMC</strong><p>Ongoing troubleshooting, preventive maintenance and CCTV AMC support.</p></article></div></section>
  <section className='seo-section seo-links'><h2>CCTV & Computer Services in Ichalkaranji</h2><div>{links.map(link=><a key={link} href={link}>{pages[link].heading}</a>)}</div></section>
  <section className='seo-section'><h2>Service Areas</h2><p>Ichalkaranji • Kolhapur • Sangli • Jaysingpur • Hatkanangale and nearby areas.</p></section>
  <footer className='seo-footer'>© {new Date().getFullYear()} Unique Market • CCTV & Security Solutions • Computer & IT Services • {ADDRESS}</footer>
 </main>
}