import React,{useEffect} from 'react'
export const pages={
'/cctv-camera-dealer-ichalkaranji':{title:'CCTV Camera Dealer in Ichalkaranji | Unique Market',heading:'CCTV Camera Dealer in Ichalkaranji',intro:'Unique Market provides CCTV cameras, security systems and professional surveillance solutions for homes, shops, offices, factories and commercial properties in Ichalkaranji.',service:'CCTV Camera Dealer',points:['Hikvision, CP Plus and Hi-Focus CCTV solutions','Indoor, outdoor, dome, bullet and IP cameras','DVR, NVR, HDD, PoE switch and networking solutions','Site survey, installation and system configuration']},
'/cctv-installation-ichalkaranji':{title:'CCTV Installation in Ichalkaranji | Unique Market',heading:'CCTV Installation in Ichalkaranji',intro:'Professional CCTV installation and configuration for residential, commercial and industrial locations across Ichalkaranji.',service:'CCTV Installation',points:['Camera placement and coverage planning','DVR/NVR setup and remote viewing configuration','Cabling, networking and PoE installation','Testing, commissioning and customer handover']},
'/cctv-service-ichalkaranji':{title:'CCTV Service in Ichalkaranji | Unique Market',heading:'CCTV Service in Ichalkaranji',intro:'Reliable CCTV service, troubleshooting and maintenance for existing surveillance systems in Ichalkaranji.',service:'CCTV Service',points:['Camera and DVR/NVR troubleshooting','HDD and recording checks','Remote viewing and network troubleshooting','System health checks and maintenance']},
'/computer-sales-service-ichalkaranji':{title:'Computer Sales & Service in Ichalkaranji | Unique Market',heading:'Computer Sales & Service in Ichalkaranji',intro:'Computer sales, setup, troubleshooting and IT support for homes, offices and businesses in Ichalkaranji.',service:'Computer Sales & Service',points:['Desktop and computer setup','Windows and driver installation','Computer troubleshooting and maintenance','Networking and peripheral support']},
'/cctv-amc-ichalkaranji':{title:'CCTV AMC in Ichalkaranji | Unique Market',heading:'CCTV AMC in Ichalkaranji',intro:'CCTV Annual Maintenance Contract solutions to keep surveillance systems monitored, maintained and operational.',service:'CCTV AMC',points:['Preventive CCTV system inspection','Camera, DVR/NVR and storage health checks','Cleaning and basic configuration support','Breakdown support and maintenance planning']}}
const links=Object.keys(pages)
export default function LocalSeoPage(){
 const path=window.location.pathname.replace(/\/$/,'')||links[0],page=pages[path]||pages[links[0]]
 useEffect(()=>{
  document.title=page.title
  const setMeta=(name,content)=>{let m=document.querySelector(`meta[name="${name}"]`);if(!m){m=document.createElement('meta');m.name=name;document.head.appendChild(m)}m.content=content}
  setMeta('description',page.intro+' Contact Unique Market, Station Road, Hotel Rajdoot, Ichalkaranji.')
  setMeta('keywords',`${page.service} in Ichalkaranji, ${page.service} Ichalkaranji, CCTV Ichalkaranji, Unique Market`)
  let c=document.querySelector('link[rel="canonical"]');if(!c){c=document.createElement('link');c.rel='canonical';document.head.appendChild(c)}c.href=`https://www.salesuniquemarket.com${path}`
  const id='seo-localbusiness-schema';let s=document.getElementById(id);if(!s){s=document.createElement('script');s.id=id;s.type='application/ld+json';document.head.appendChild(s)}s.textContent=JSON.stringify({'@context':'https://schema.org','@type':'LocalBusiness','name':'Unique Market','url':`https://www.salesuniquemarket.com${path}`,'telephone':'+918554887026','address':{'@type':'PostalAddress','streetAddress':'Station Road, Hotel Rajdoot','addressLocality':'Ichalkaranji','addressRegion':'Maharashtra','postalCode':'416115','addressCountry':'IN'},'areaServed':'Ichalkaranji','serviceType':page.service})
 },[page,path])
 return <main className='seo-page'><header className='seo-header'><a className='seo-brand' href='/'>UNIQUE MARKET</a><a className='seo-login' href='/login'>Customer / Technician Login</a></header><section className='seo-hero'><span className='seo-badge'>ICHALKARANJI • CCTV & IT SECURITY</span><h1>{page.heading}</h1><p>{page.intro}</p><div className='seo-actions'><a href={`tel:+918554887026`}>Call +91 8554887026</a><a href={`https://wa.me/918554887026`}>WhatsApp Us</a></div></section><section className='seo-section'><h2>{page.service} in Ichalkaranji</h2><p>Unique Market delivers practical security and IT solutions with installation, configuration and support for customers in Ichalkaranji and nearby areas. We help with product selection, site requirements, installation, troubleshooting and ongoing maintenance.</p><div className='seo-grid'>{page.points.map(point=><article key={point}><strong>{point}</strong><p>Professional support focused on reliable installation and service.</p></article>)}</div></section><section className='seo-section seo-links'><h2>Our Ichalkaranji Services</h2><div>{links.map(link=><a key={link} href={link}>{pages[link].heading}</a>)}</div></section><footer className='seo-footer'>© {new Date().getFullYear()} Unique Market • CCTV & Security Solutions • Station Road, Hotel Rajdoot, Ichalkaranji, Maharashtra</footer></main>}