import {useMemo,useState} from 'react'
import {Activity,AlertTriangle,BrainCircuit,CheckCircle2,Network,Router,ScanLine,ShieldCheck,Wifi,WifiOff} from 'lucide-react'
const demoDevices=[{ip:'192.168.1.1',name:'Gateway / Router',type:'Router',status:'online',mac:'—'},{ip:'192.168.1.10',name:'NVR',type:'NVR',status:'online',mac:'—'},{ip:'192.168.1.11',name:'Camera 01',type:'IP Camera',status:'conflict',mac:'MAC-A / MAC-B'},{ip:'192.168.1.12',name:'Camera 02',type:'IP Camera',status:'online',mac:'—'},{ip:'192.168.1.20',name:'Office Printer',type:'Printer',status:'online',mac:'—'}]
export default function NetworkAITool({onBack}){
 const[scanning,setScanning]=useState(false),[scanned,setScanned]=useState(false),[agent,setAgent]=useState(false),[query,setQuery]=useState('')
 const devices=useMemo(()=>demoDevices.filter(d=>`${d.ip} ${d.name} ${d.type}`.toLowerCase().includes(query.toLowerCase())),[query]);const conflicts=demoDevices.filter(d=>d.status==='conflict').length
 const scan=()=>{setScanning(true);setTimeout(()=>{setScanning(false);setScanned(true)},1200)}
 return <section className='network-ai-shell'><div className='network-ai-head'><div><span className='dashboard-kicker'>UNIQUE MARKET • FIELD TOOL</span><h2><BrainCircuit size={30}/> Network AI Doctor</h2><p>LAN discovery, CCTV IP planning, conflict diagnosis and guided network repair.</p></div><div className='network-ai-actions'><button className='secondary' onClick={onBack}>← Back</button><button className='primary' onClick={scan} disabled={scanning}><ScanLine size={18}/>{scanning?'Scanning LAN…':'Scan Network'}</button></div></div>
 <div className={`agent-banner ${agent?'agent-ok':''}`}><div><strong>{agent?'Local Network Agent connected':'Local Network Agent not connected'}</strong><span>{agent?'Direct LAN diagnostics are available.':'A browser alone cannot safely scan or reconfigure the LAN. The Windows Local Agent is required for real device discovery and IP changes.'}</span></div><button onClick={()=>setAgent(v=>!v)}>{agent?'Disconnect':'Connect Agent'}</button></div>
 <div className='network-ai-grid'><article className='ai-panel ai-overview'><div className='ai-panel-title'><Activity/> Network Health</div><div className='health-score'>{scanned?'78':'—'}<small>/100</small></div><div className='health-row'><span><CheckCircle2/> Reachable</span><strong>{scanned?'4':'—'}</strong></div><div className='health-row'><span><AlertTriangle/> IP conflicts</span><strong>{scanned?conflicts:'—'}</strong></div><div className='health-row'><span><WifiOff/> Offline</span><strong>{scanned?'0':'—'}</strong></div></article>
 <article className='ai-panel'><div className='ai-panel-title'><BrainCircuit/> AI Diagnosis</div>{scanned?<><div className='diagnosis danger'><AlertTriangle/><div><strong>Possible IP conflict</strong><p>192.168.1.11 appears to have conflicting identity. Do not change a PC/printer automatically.</p></div></div><div className='diagnosis safe'><ShieldCheck/><div><strong>Safe camera IP</strong><p>Suggested next free address: <b>192.168.1.13</b></p></div></div><button className='fix-button' onClick={()=>alert('Guided repair requires the connected local agent and confirmation before changing any device.')}>Review & Fix Safely</button></>:<div className='empty-ai'>Run a LAN scan to let the AI analyze subnet, DHCP overlap, duplicate IPs, unreachable devices and CCTV addressing.</div>}</article>
 <article className='ai-panel'><div className='ai-panel-title'><Network/> CCTV IP Planner</div><label>New cameras</label><input type='number' min='1' max='256' defaultValue='16'/><label>Preferred range</label><div className='range-inputs'><input defaultValue='192.168.1.101'/><span>→</span><input defaultValue='192.168.1.116'/></div><button className='planner-button' onClick={()=>alert('Planner ready. With the local agent connected it will reserve only verified-free addresses.')}>Find Conflict-Free IPs</button></article></div>
 <div className='ai-panel device-panel'><div className='device-toolbar'><div className='ai-panel-title'><Router/> Discovered Devices</div><input placeholder='Search IP, device or type…' value={query} onChange={e=>setQuery(e.target.value)}/></div><div className='device-table'>{devices.map(d=><div className='device-row' key={d.ip}><span className='device-ip'>{d.ip}</span><span><strong>{d.name}</strong><small>{d.type} • {d.mac}</small></span><span className={`device-status ${d.status}`}>{d.status==='conflict'?<AlertTriangle size={15}/>:<CheckCircle2 size={15}/>} {d.status}</span></div>)}</div>{!scanned&&<div className='scan-hint'><Wifi size={18}/> Connect the Local Network Agent, then run Scan Network for live LAN results.</div>}</div></section>
}