import {useMemo,useState} from 'react'
import {Activity,AlertTriangle,BrainCircuit,CheckCircle2,Network,Router,ScanLine,ShieldCheck,Wifi,WifiOff,Zap} from 'lucide-react'
const AGENT='http://127.0.0.1:17855'
export default function NetworkAITool({onBack}){
 const[scanning,setScanning]=useState(false),[connected,setConnected]=useState(false),[data,setData]=useState(null),[error,setError]=useState(''),[query,setQuery]=useState(''),[count,setCount]=useState(16),[planned,setPlanned]=useState([]),[user,setUser]=useState(''),[pass,setPass]=useState(''),[autoBusy,setAutoBusy]=useState(false),[autoResult,setAutoResult]=useState('')
 const devices=useMemo(()=>data?.devices||[],[data]);const cameras=devices.filter(d=>d.type==='IP Camera'&&d.protocol==='ONVIF');const filtered=devices.filter(d=>`${d.ip} ${d.name||''} ${d.type||''} ${d.mac||''}`.toLowerCase().includes(query.toLowerCase()))
 async function connect(){try{setError('');const r=await fetch(`${AGENT}/api/status`);if(!r.ok)throw Error('Agent unavailable');setConnected(true)}catch{setConnected(false);setError('Local Network Agent is not running. Start the Windows agent, then connect again.')}}
 async function scan(){setScanning(true);setError('');setPlanned([]);try{const r=await fetch(`${AGENT}/api/scan`);const j=await r.json();if(!r.ok)throw Error(j.error||'Scan failed');setData(j);setConnected(true)}catch(e){setError(e.message||'Unable to scan LAN.');setConnected(false)}finally{setScanning(false)}}
 async function plan(){if(!data)return;setError('');try{const used=devices.map(d=>d.ip);const r=await fetch(`${AGENT}/api/ip-plan`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({subnet:data.subnet,usedIps:used,count})});const j=await r.json();if(!r.ok)throw Error(j.error||'Planner failed');setPlanned(j.ips||[])}catch(e){setError(e.message)}}
 async function autoAssign(){if(!cameras.length||!planned.length)return setError('Run scan and IP planner first.');if(!user||!pass)return setError('Enter the camera ONVIF username and password.');setAutoBusy(true);setAutoResult('');let ok=0,fail=0;for(let i=0;i<Math.min(cameras.length,planned.length);i++){const c=cameras[i],url=c.xaddrs?.find(x=>/^https?:/i.test(x));if(!url){fail++;continue}try{const r=await fetch(`${AGENT}/api/auto-camera-ip`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({url,username:user,password:pass,newIp:planned[i],prefixLength:Number((data.subnet||'/24').split('/')[1]||24),confirm:true})});if(r.ok)ok++;else fail++}catch{fail++}}setAutoBusy(false);setAutoResult(`${ok} camera(s) configured, ${fail} failed. Re-scan the LAN before continuing.`)}
 return <section className='network-ai-shell'><div className='network-ai-head'><div><span className='dashboard-kicker'>UNIQUE MARKET • FIELD TOOL</span><h2><BrainCircuit size={30}/> Network AI Doctor</h2><p>Automatic LAN discovery, CCTV IP planning, conflict diagnosis and guided network repair.</p></div><div className='network-ai-actions'><button className='secondary' onClick={onBack}>← Back</button><button className='primary' onClick={scan} disabled={scanning||!connected}><ScanLine size={18}/>{scanning?'Scanning LAN…':'Scan Network'}</button></div></div>
 <div className={`agent-banner ${connected?'agent-ok':''}`}><div><strong>{connected?'Local Network Agent connected':'Local Network Agent not connected'}</strong><span>{connected?'Live LAN diagnostics are available on this PC.':'Connect the Windows Local Network Agent for automatic discovery and CCTV configuration.'}</span></div><button onClick={connect}>{connected?'Test Connection':'Connect Agent'}</button></div>{error&&<div className='agent-banner'><strong>{error}</strong></div>}
 <div className='network-ai-grid'><article className='ai-panel ai-overview'><div className='ai-panel-title'><Activity/> Network Health</div><div className='health-score'>{data?100:'—'}<small>/100</small></div><div className='health-row'><span><CheckCircle2/> Reachable</span><strong>{data?devices.length:'—'}</strong></div><div className='health-row'><span><AlertTriangle/> ONVIF cameras</span><strong>{data?cameras.length:'—'}</strong></div><div className='health-row'><span><WifiOff/> Offline</span><strong>{data?'Not inferred':'—'}</strong></div></article>
 <article className='ai-panel'><div className='ai-panel-title'><BrainCircuit/> AI Diagnosis</div>{data?<><div className='diagnosis safe'><ShieldCheck/><div><strong>LAN scan complete</strong><p>{data.subnet} • {devices.length} responding device(s) • {data.onvifCount||0} ONVIF camera(s).</p></div></div><div className='diagnosis'><Network/><div><strong>Automatic mode ready</strong><p>Free IPs are planned only after the current scan. Camera IP changes are restricted to detected ONVIF cameras.</p></div></div></>:<div className='empty-ai'>Connect the local agent and scan. The AI will use live LAN data instead of demo devices.</div>}</article>
 <article className='ai-panel'><div className='ai-panel-title'><Zap/> Automatic CCTV IP</div><label>New cameras</label><input type='number' min='1' max='254' value={count} onChange={e=>setCount(Number(e.target.value)||1)}/><button className='planner-button' onClick={plan} disabled={!data}>Find & Reserve Free IPs</button>{planned.length>0&&<><div className='planned-ips'>{planned.join(' • ')}</div><label>ONVIF username</label><input value={user} onChange={e=>setUser(e.target.value)} placeholder='Camera username'/><label>ONVIF password</label><input type='password' value={pass} onChange={e=>setPass(e.target.value)} placeholder='Camera password'/><button className='fix-button' onClick={autoAssign} disabled={autoBusy||!cameras.length}>{autoBusy?'Configuring cameras…':'⚡ Auto Assign Camera IPs'}</button>{autoResult&&<small>{autoResult}</small>}</>}</article></div>
 <div className='ai-panel device-panel'><div className='device-toolbar'><div className='ai-panel-title'><Router/> Discovered Devices</div><input placeholder='Search IP, device, MAC or type…' value={query} onChange={e=>setQuery(e.target.value)}/></div><div className='device-table'>{filtered.map(d=><div className='device-row' key={`${d.ip}-${d.mac||''}`}><span className='device-ip'>{d.ip}</span><span><strong>{d.type==='IP Camera'?'IP Camera':d.name||'Unknown LAN device'}</strong><small>{d.type||'IPv4 host'}{d.mac?` • ${d.mac}`:''}{d.protocol?` • ${d.protocol}`:''}</small></span><span className='device-status online'><CheckCircle2 size={15}/> online</span></div>)}</div>{!data&&<div className='scan-hint'><Wifi size={18}/> Connect the Local Agent first.</div>}</div></section>
}