import {useMemo,useState} from 'react'
import {Activity,AlertTriangle,BrainCircuit,CheckCircle2,Network,Router,ScanLine,ShieldCheck,Wifi,WifiOff} from 'lucide-react'
const AGENT='http://127.0.0.1:17855'
export default function NetworkAITool({onBack}){
 const[scanning,setScanning]=useState(false),[connected,setConnected]=useState(false),[data,setData]=useState(null),[error,setError]=useState(''),[query,setQuery]=useState('')
 const devices=useMemo(()=>data?.devices||[],[data]);const filtered=devices.filter(d=>`${d.ip} ${d.name||''} ${d.type||''}`.toLowerCase().includes(query.toLowerCase()))
 async function connect(){try{setError('');const r=await fetch(`${AGENT}/api/status`);if(!r.ok)throw Error('Agent unavailable');setConnected(true)}catch{setConnected(false);setError('Local Network Agent is not running. Start the Windows agent, then connect again.')}}
 async function scan(){setScanning(true);setError('');try{const r=await fetch(`${AGENT}/api/scan`);const j=await r.json();if(!r.ok)throw Error(j.error||'Scan failed');setData(j);setConnected(true)}catch(e){setError(e.message||'Unable to scan LAN.');setConnected(false)}finally{setScanning(false)}}
 return <section className='network-ai-shell'><div className='network-ai-head'><div><span className='dashboard-kicker'>UNIQUE MARKET • FIELD TOOL</span><h2><BrainCircuit size={30}/> Network AI Doctor</h2><p>LAN discovery, CCTV IP planning, conflict diagnosis and guided network repair.</p></div><div className='network-ai-actions'><button className='secondary' onClick={onBack}>← Back</button><button className='primary' onClick={scan} disabled={scanning||!connected}><ScanLine size={18}/>{scanning?'Scanning LAN…':'Scan Network'}</button></div></div>
 <div className={`agent-banner ${connected?'agent-ok':''}`}><div><strong>{connected?'Local Network Agent connected':'Local Network Agent not connected'}</strong><span>{connected?'Live LAN diagnostics are available on this PC.':'The browser cannot directly scan/reconfigure a LAN. Connect the Windows Local Network Agent for real discovery.'}</span></div><button onClick={connect}>{connected?'Test Connection':'Connect Agent'}</button></div>{error&&<div className='agent-banner'><strong>{error}</strong></div>}
 <div className='network-ai-grid'><article className='ai-panel ai-overview'><div className='ai-panel-title'><Activity/> Network Health</div><div className='health-score'>{data?Math.max(0,100-Math.min(80,(devices.length?0:30))):'—'}<small>/100</small></div><div className='health-row'><span><CheckCircle2/> Reachable</span><strong>{data?devices.length:'—'}</strong></div><div className='health-row'><span><AlertTriangle/> Conflicts</span><strong>{data?'Scan ARP for verification':'—'}</strong></div><div className='health-row'><span><WifiOff/> Offline</span><strong>{data?'Not inferred':'—'}</strong></div></article>
 <article className='ai-panel'><div className='ai-panel-title'><BrainCircuit/> AI Diagnosis</div>{data?<><div className='diagnosis safe'><ShieldCheck/><div><strong>LAN discovered successfully</strong><p>{data.subnet||'IPv4 LAN'} • {devices.length} responding device(s).</p></div></div><div className='diagnosis'><Network/><div><strong>Next diagnostic pass</strong><p>Use ARP/MAC + ONVIF/vendor discovery to classify cameras, NVRs, printers and detect duplicate/static-IP conflicts.</p></div></div><button className='fix-button' onClick={()=>alert('Safe repair mode is intentionally gated. Device IP changes require verified device identity and explicit confirmation.')}>Review Safe Fixes</button></>:<div className='empty-ai'>Connect the local agent, then scan. The AI layer will analyze subnet, DHCP/static overlap, duplicate IP evidence, unreachable devices and CCTV addressing.</div>}</article>
 <article className='ai-panel'><div className='ai-panel-title'><Network/> CCTV IP Planner</div><label>New cameras</label><input type='number' min='1' max='256' defaultValue='16'/><label>Preferred range</label><div className='range-inputs'><input defaultValue='192.168.1.101'/><span>→</span><input defaultValue='192.168.1.116'/></div><button className='planner-button' onClick={()=>alert('Planner will only reserve IPs verified free by the local agent.')}>Find Conflict-Free IPs</button></article></div>
 <div className='ai-panel device-panel'><div className='device-toolbar'><div className='ai-panel-title'><Router/> Discovered Devices</div><input placeholder='Search IP, device or type…' value={query} onChange={e=>setQuery(e.target.value)}/></div><div className='device-table'>{filtered.map(d=><div className='device-row' key={d.ip}><span className='device-ip'>{d.ip}</span><span><strong>{d.name||'Unknown LAN device'}</strong><small>{d.type||'IPv4 host'}{d.source?` • ${d.source}`:''}</small></span><span className='device-status online'><CheckCircle2 size={15}/> online</span></div>)}</div>{!data&&<div className='scan-hint'><Wifi size={18}/> No live scan data yet. Connect the Local Agent first.</div>}</div></section>
}