import {useEffect,useState} from 'react'
import {roleLabel} from '../lib/roles'
import {supabase} from '../lib/supabase'

const adminModules=[['Reports','Business performance and service insights'],['Complaints','Manage and track customer complaints'],['Customers','View and manage customer records'],['Technicians','Manage technician assignments and work'],['User Accounts','Create and manage portal accounts'],['Payments','Track customer payments and collections'],['Products','Manage CCTV and IT products'],['AMC','Manage AMC contracts and renewals'],['Settings','Configure portal settings']]
const modules={admin:adminModules,technician:[['My Assigned Complaints','View complaints assigned to you'],['Find Complaint','Search and manage service tickets'],["Today's Visits",'View your scheduled service visits'],['Raise Request','Send a support request to Admin'],['Service History','Review your completed service work'],['Collect Payment','Collect cash or UPI payment'],['My Profile','Manage your technician profile']],customer:[['Raise Complaint','Get CCTV & security support quickly'],['My Complaints','Track your service tickets'],['Service History','View your previous service records'],['AMC Details','Check AMC coverage and contract'],['Payments','View payments and transaction details'],['My Profile','Manage your customer profile']]}
const countTables={complaints:'complaints',customers:'customers',technicians:'technicians',payments:'payments'}
const iconMap={'Raise Complaint':'🔧','My Complaints':'🎫','Service History':'↩','AMC Details':'🛡','Payments':'💳','My Profile':'👤',Reports:'📊',Complaints:'🎫',Customers:'👥',Technicians:'🛠','User Accounts':'👤',Products:'📦',AMC:'🛡',Settings:'⚙','Find Complaint':'🔎',"Today's Visits":'📅','Collect Payment':'💳','Raise Request':'📝'}
export default function RoleDashboard({profile,onSelectModule}){
 const role=profile?.role;const items=role&&modules[role]?modules[role]:[];const[counts,setCounts]=useState({})
 useEffect(()=>{let cancelled=false;(async()=>{if(role!=='admin')return;const entries=await Promise.all(Object.entries(countTables).map(async([key,table])=>{const{count}=await supabase.from(table).select('*',{count:'exact',head:true});return[key,count||0]}));if(!cancelled)setCounts(Object.fromEntries(entries))})();return()=>{cancelled=true}},[role])
 return <section className={`role-dashboard role-dashboard--${role||'guest'}`}><div className='dashboard-heading'><div><span className='dashboard-kicker'>SECURE SERVICE PORTAL</span><div className='dashboard-title-row'><h2>{roleLabel(role)} Dashboard</h2><span className='dashboard-live'><span/>LIVE</span></div><p className='dashboard-subtitle'>Your complete CCTV & security service command center. Everything you need, right at your fingertips.</p></div></div>{role==='admin'&&<div className='admin-stats'>{Object.entries(counts).map(([key,value])=><div className='dashboard-stat-card' key={key}><div><strong>{value}</strong><span>{key.charAt(0).toUpperCase()+key.slice(1)}</span></div></div>)}</div>}<div className='dashboard-section-label'><span>QUICK ACTIONS</span><i/></div><div className='modules'>{items.map(([item,description],index)=><button key={item} type='button' className={`module-card module-card--${index+1}`} onClick={()=>onSelectModule?.(role==='customer'&&item==='My Complaints'?'__MY_COMPLAINTS__':item)}><div className='module-card-glow'/><div className='module-icon' aria-hidden='true'>{iconMap[item]||'•'}</div><div className='module-card-copy'><h3>{item}</h3><p>{description}</p></div><span className='module-arrow' aria-hidden='true'>→</span></button>)}</div></section>
}