import {useEffect,useMemo,useState} from 'react'
import {supabase} from '../lib/supabase'

const FALLBACK_UPI='sohammane855-8@okhdfcbank'

export default function TechnicianPayment({profile,onBack}){
 const [customers,setCustomers]=useState([]),[customerId,setCustomerId]=useState(''),[amount,setAmount]=useState(''),[referenceNo,setReferenceNo]=useState(''),[notes,setNotes]=useState(''),[settings,setSettings]=useState(null),[saving,setSaving]=useState(false),[message,setMessage]=useState('')
 useEffect(()=>{(async()=>{const[{data:cs},{data:ps}]=await Promise.all([supabase.from('customers').select('id,name,mobile').order('name').limit(500),supabase.from('payment_settings').select('upi_id,account_name,qr_image_url,is_enabled').limit(1).maybeSingle()]);setCustomers(cs||[]);setSettings(ps||null)})()},[])
 const upiId=settings?.upi_id||FALLBACK_UPI,accountName=settings?.account_name||'Unique Market'
 const qrUrl=useMemo(()=>`https://api.qrserver.com/v1/create-qr-code/?size=280x280&data=${encodeURIComponent(`upi://pay?pa=${encodeURIComponent(upiId)}&pn=${encodeURIComponent(accountName)}&cu=INR`)}`,[upiId,accountName])
 async function submit(e){e.preventDefault();setMessage('');if(!customerId||!amount||Number(amount)<=0)return setMessage('Select customer and enter a valid amount.');if(!referenceNo.trim())return setMessage('Customer UTR / reference number is required.');setSaving(true);const{error}=await supabase.from('payments').insert({customer_id:customerId,payment_date:new Date().toISOString().slice(0,10),amount:Number(amount),mode:'UPI',status:'pending',source:'technician',recorded_by:profile.id,reference_no:referenceNo.trim(),notes:notes.trim()||'Customer QR payment — verification pending'});setSaving(false);if(error){setMessage(error.message);return}setMessage('UTR submitted. Payment is Verification Pending. Call can close only after payment verification.');setAmount('');setReferenceNo('');setNotes('')}
 return <section className='role-dashboard'><button className='secondary' type='button' onClick={onBack}>← Dashboard</button><div className='admin-panel'><div className='panel-heading'><div><span className='badge'>TECHNICIAN • CUSTOMER PAYMENT</span><h2>Customer QR Payment</h2><p>Customer scans the Unique Market QR and pays directly to the company account. Technician only enters the UTR / reference number.</p></div></div>{message&&<p className={message.startsWith('UTR submitted')?'muted':'error'}>{message}</p>}<form className='admin-form' onSubmit={submit}><label>Customer<select value={customerId} onChange={e=>setCustomerId(e.target.value)}><option value=''>Select customer</option>{customers.map(c=><option key={c.id} value={c.id}>{c.name}{c.mobile?' • '+c.mobile:''}</option>)}</select></label><div style={{textAlign:'center',padding:'10px 0 16px'}}><strong>Scan & Pay to Unique Market</strong><p className='muted' style={{margin:'5px 0'}}>UPI: {upiId}</p><img src={settings?.qr_image_url||qrUrl} alt='Unique Market UPI QR' style={{width:220,height:220,objectFit:'contain',border:'1px solid #ddd',borderRadius:12}}/><p className='muted' style={{margin:'8px 0 0'}}>After customer payment, enter the UTR below.</p></div><label>Payment Amount<input type='number' min='1' step='0.01' value={amount} onChange={e=>setAmount(e.target.value)} placeholder='₹ Amount paid by customer'/></label><label>Customer UTR / Reference No.<input required value={referenceNo} onChange={e=>setReferenceNo(e.target.value)} placeholder='Enter UTR / transaction reference'/></label><label>Notes (optional)<input value={notes} onChange={e=>setNotes(e.target.value)} placeholder='Optional payment notes'/></label><button disabled={saving||!customerId||!amount||!referenceNo.trim()}>{saving?'Submitting…':'Submit UTR for Verification'}</button></form></div></section>
}
