import { useEffect, useMemo, useState } from 'react'
import { supabase } from '../lib/supabase'
import { subscribeToComplaints } from '../lib/realtime'

const statusLabel={open:'NEW REQUEST',assigned:'ASSIGNED',in_progress:'IN PROGRESS',resolved:'SERVICE COMPLETED',closed:'CLOSED'}
const FALLBACK_UPI='sohammane855-8@okhdfcbank'

export default function TechnicianModule({profile,mode='assigned',onBack}){
 const[items,setItems]=useState([]),[query,setQuery]=useState(''),[searchType,setSearchType]=useState('name'),[fromDate,setFromDate]=useState(''),[toDate,setToDate]=useState(''),[loading,setLoading]=useState(true),[message,setMessage]=useState(''),[paymentFor,setPaymentFor]=useState(null),[payment,setPayment]=useState({amount:'',mode:'UPI',reference_no:'',notes:''}),[notifications,setNotifications]=useState([]),[paymentSettings,setPaymentSettings]=useState(null),[paymentStatus,setPaymentStatus]=useState('')
 const[cashToday,setCashToday]=useState(0),[upiToday,setUpiToday]=useState(0),[totalToday,setTotalToday]=useState(0),[todayPayments,setTodayPayments]=useState([])

 async function loadPaymentSettings(){if(!supabase)return;const{data}=await supabase.from('payment_settings').select('upi_id,account_name,qr_image_url,is_enabled').limit(1).maybeSingle();if(data)setPaymentSettings(data)}
 async function loadPaymentsToday(){if(!supabase||!profile?.id)return;const today=new Date().toISOString().slice(0,10);const{data,error}=await supabase.from('payments').select('id,customer_id,amount,mode,reference_no,status,payment_date,created_at,notes,recorded_by,source').eq('payment_date',today).eq('status','confirmed').eq('recorded_by',profile.id).order('created_at',{ascending:false}).limit(200);if(error){setMessage(error.message);return}const rows=data||[];setCashToday(rows.filter(p=>String(p.mode||'').toUpperCase()==='CASH').reduce((s,p)=>s+Number(p.amount||0),0));setUpiToday(rows.filter(p=>String(p.mode||'').toUpperCase()==='UPI').reduce((s,p)=>s+Number(p.amount||0),0));setTotalToday(rows.reduce((s,p)=>s+Number(p.amount||0),0));setTodayPayments(rows)}
 async function loadNotifications(){if(!supabase||!profile?.id)return;const{data,error}=await supabase.from('notifications').select('id,title,message,type,read_at,created_at,complaint_id').eq('user_id',profile.id).is('read_at',null).order('created_at',{ascending:false}).limit(10);if(!error)setNotifications(data||[])}
 async function load(search=query,type=searchType,from=fromDate,to=toDate){if(!supabase||!profile?.id)return;setLoading(true);setMessage('');let q=supabase.from('complaints').select('id,complaint_no,ticket_no,title,description,category,priority,status,location_text,address,created_at,customer_name,customer_phone,company_name,technician_id,customer_id,started_at,completed_at,resolution_notes,assigned_at,scheduled_visit_date').eq('technician_id',profile.id).order('scheduled_visit_date',{ascending:true,nullsFirst:false}).order('created_at',{ascending:false});if(mode==='today'){const today=new Date().toISOString().slice(0,10);q=q.eq('scheduled_visit_date',today);await Promise.all([loadPaymentsToday(),loadNotifications()])}else if(mode==='find'){if(type==='name'&&search.trim())q=q.ilike('customer_name',`%${search.trim()}%`);if(type==='code'&&search.trim())q=q.or(`complaint_no.ilike.%${search.trim()}%,ticket_no.ilike.%${search.trim()}%`);if(type==='date'&&from)q=q.gte('created_at',`${from}T00:00:00`).lte('created_at',`${to||from}T23:59:59`)}const{data,error}=await q;if(error)setMessage(error.message);else setItems(data||[]);setLoading(false)}
 useEffect(()=>{if(!profile?.id)return;loadPaymentSettings();load('',searchType,fromDate,toDate);if('Notification' in window&&Notification.permission==='default')Notification.requestPermission().catch(()=>{});const complaintChannel=subscribeToComplaints(()=>load());const notificationChannel=supabase.channel(`technician-notifications-${profile.id}`).on('postgres_changes',{event:'INSERT',schema:'public',table:'notifications',filter:`user_id=eq.${profile.id}`},payload=>{const n=payload.new;setNotifications(prev=>[n,...prev].slice(0,10));setMessage(`🔔 ${n.title}: ${n.message}`);if('Notification' in window&&Notification.permission==='granted'){try{new Notification(n.title,{body:n.message})}catch{}}load()}).subscribe();return()=>{complaintChannel();supabase.removeChannel(notificationChannel)}},[profile?.id,mode])
 useEffect(()=>{if(!paymentFor||!payment.reference_no.trim())return;let cancelled=false;const check=async()=>{const{data,error}=await supabase.from('payments').select('id,status,amount,reference_no').eq('recorded_by',profile.id).eq('reference_no',payment.reference_no.trim()).order('created_at',{ascending:false}).limit(1).maybeSingle();if(cancelled||error||!data)return;if(data.status==='confirmed'){setPaymentStatus('Payment verified successfully. You can close the call now.');setMessage('Payment verified successfully.');await supabase.from('complaints').update({status:'closed',updated_at:new Date().toISOString()}).eq('id',paymentFor.id).eq('technician_id',profile.id);setPaymentFor(null);setPaymentStatus('');setPayment({amount:'',mode:'UPI',reference_no:'',notes:''});await loadPaymentsToday();load()}else if(data.status==='rejected'){setPaymentStatus('Payment verification rejected. Check the UTR and try again.')}};check();const timer=setInterval(check,5000);return()=>{cancelled=true;clearInterval(timer)}},[paymentFor,payment.reference_no,profile?.id])
 async function markNotificationRead(id){await supabase.from('notifications').update({read_at:new Date().toISOString()}).eq('id',id).eq('user_id',profile.id);setNotifications(prev=>prev.filter(n=>n.id!==id))}
 async function setStatus(item,status,extra={}){setMessage('');const{error}=await supabase.from('complaints').update({status,updated_at:new Date().toISOString(),...extra}).eq('id',item.id).eq('technician_id',profile.id);if(error)setMessage(error.message);else load()}
 async function claimJob(item){const{error}=await supabase.from('complaints').update({technician_id:profile.id,status:'assigned',assigned_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('id',item.id).is('technician_id',null).eq('status','open');if(error)setMessage(error.message);else load()}
 async function acceptJob(item){await setStatus(item,'in_progress',{started_at:new Date().toISOString()})}
 async function completeService(item){const notes=window.prompt('Service completion notes (optional):',item.resolution_notes||'');if(notes===null)return;await setStatus(item,'resolved',{completed_at:new Date().toISOString(),resolution_notes:notes})}
 async function collectPayment(){if(!paymentFor||!supabase)return;const amount=Number(payment.amount);if(!amount||amount<=0)return setMessage('Enter a valid payment amount.');if(!payment.reference_no.trim())return setMessage('Customer payment UTR / reference number is required.');const{data:complaint,error:complaintError}=await supabase.from('complaints').select('id,customer_id,customer_name,complaint_no').eq('id',paymentFor.id).maybeSingle();if(complaintError)return setMessage(complaintError.message);if(!complaint?.customer_id)return setMessage('Customer is not linked to this complaint. Please contact admin.');const{data:customer,error:customerError}=await supabase.from('customers').select('id').eq('id',complaint.customer_id).maybeSingle();if(customerError)return setMessage(customerError.message);if(!customer?.id)return setMessage('Customer record does not exist for this complaint.');const{error}=await supabase.from('payments').insert({customer_id:customer.id,amount,mode:'UPI',reference_no:payment.reference_no.trim(),notes:`Customer QR payment for ${complaint.complaint_no||paymentFor.complaint_no||paymentFor.id}${payment.notes.trim()?` — ${payment.notes.trim()}`:''}`,recorded_by:profile.id,status:'pending',source:'technician',payment_date:new Date().toISOString().slice(0,10)});if(error)return setMessage(error.message);setPaymentStatus('UTR submitted. Waiting for payment verification. Call will close automatically after Admin/payment verification.');setMessage('Payment submitted for verification. Do not close the call manually.');await loadPaymentsToday()}
 const displayNo=i=>i.complaint_no||i.ticket_no||`C/NO-${i.id}`
 const upiId=paymentSettings?.upi_id||FALLBACK_UPI,accountName=paymentSettings?.account_name||'Unique Market'
 const qrUrl=useMemo(()=>{const upi=`upi://pay?pa=${encodeURIComponent(upiId)}&pn=${encodeURIComponent(accountName)}&cu=INR`;return `https://api.qrserver.com/v1/create-qr-code/?size=280x280&data=${encodeURIComponent(upi)}`},[upiId,accountName])
 return <section className='complaints-panel'><div className='panel-heading'><div><span className='badge'>TECHNICIAN DESK</span><h2>{mode==='find'?'Find Complaint':mode==='today'?"Today's Visits":'Live Service Requests'}</h2><p>{mode==='find'?'Search only by Party / Customer Name, Complaint Code or Date-wise.':mode==='today'?"Today's scheduled visits and collection summary.":'Customer-raised open requests and complaints assigned to you.'}</p></div><div><span className='status'>LIVE</span> <button className='secondary' type='button' onClick={onBack}>← Back</button></div></div>
 {mode==='today'&&notifications.length>0&&<div className='module-card' style={{margin:'18px 0'}}><h3>🔔 New Notifications</h3>{notifications.map(n=><div key={n.id} style={{display:'flex',justifyContent:'space-between',gap:10,alignItems:'center',padding:'8px 0',borderBottom:'1px solid #eee'}}><div><strong>{n.title}</strong><p style={{margin:'3px 0'}}>{n.message}</p></div><button className='secondary' type='button' onClick={()=>markNotificationRead(n.id)}>Mark read</button></div>)}</div>}
 {mode==='today'&&<div className='admin-stats' style={{margin:'18px 0'}}><div className='stat-card'><strong>₹{cashToday.toLocaleString('en-IN')}</strong><span>Cash Collected Today</span></div><div className='stat-card'><strong>₹{upiToday.toLocaleString('en-IN')}</strong><span>Company QR / UPI Today</span></div><div className='stat-card'><strong>₹{totalToday.toLocaleString('en-IN')}</strong><span>Total Collected Today</span></div></div>}
 {mode==='find'&&<form className='search-row' onSubmit={e=>{e.preventDefault();load(query,searchType,fromDate,toDate)}} style={{display:'flex',gap:8,margin:'18px 0',flexWrap:'wrap'}}><select value={searchType} onChange={e=>{setSearchType(e.target.value);setQuery('');setFromDate('');setToDate('');setItems([])}}><option value='name'>Party / Customer Name</option><option value='code'>Complaint Code</option><option value='date'>Date-wise Search</option></select>{searchType==='date'?<><input type='date' value={fromDate} onChange={e=>setFromDate(e.target.value)}/><input type='date' value={toDate} onChange={e=>setToDate(e.target.value)}/></>:<input value={query} onChange={e=>setQuery(e.target.value)} placeholder={searchType==='name'?'Enter Party / Customer Name':'Enter Complaint Code'}/>}<button type='submit'>Find Complaint</button></form>}
 {message&&<p className={message.includes('successfully')?'muted':'error'}>{message}</p>}
 {mode==='today'&&todayPayments.length>0&&<div className='module-card' style={{marginBottom:18}}><h3>Today's Payment History</h3>{todayPayments.map(p=><p key={p.id}>₹{Number(p.amount||0).toLocaleString('en-IN')} · {p.mode||'—'} · {p.reference_no||'—'}</p>)}</div>}
 {loading?<p>Loading…</p>:items.length===0?<div className='module-card'><h3>{mode==='today'?'No visits scheduled for today':'No visits found'}</h3></div>:<div className='modules'>{items.map(item=><article className='module-card' key={item.id}><span className='status'>{displayNo(item)} · {statusLabel[item.status]||'OPEN'}{item.scheduled_visit_date?` · Visit ${item.scheduled_visit_date}`:''}</span><h3>{item.title||item.description||'Service Complaint'}</h3><p><strong>Customer:</strong> {item.customer_name||'—'} · {item.customer_phone||'—'}</p><p><strong>Company:</strong> {item.company_name||'—'}</p><p><strong>Address:</strong> {item.location_text||item.address||'—'}</p><p>{item.description||'No additional description.'}</p><div style={{display:'flex',gap:8,flexWrap:'wrap',marginTop:12}}>{item.status==='open'&&!item.technician_id&&<button type='button' onClick={()=>claimJob(item)}>✓ Accept Request</button>}{item.status==='assigned'&&item.technician_id===profile.id&&<button type='button' onClick={()=>acceptJob(item)}>✓ Start Service</button>}{item.status==='in_progress'&&item.technician_id===profile.id&&<button type='button' onClick={()=>completeService(item)}>✓ Service Completed</button>}{item.status==='resolved'&&item.technician_id===profile.id&&<button type='button' onClick={()=>{setPaymentFor(item);setPaymentStatus('');setMessage('')}}>💳 Customer Payment & Close</button>}{item.status==='closed'&&<strong>✓ Service File Closed</strong>}</div></article>)}</div>}
 {paymentFor&&<div role='dialog' aria-modal='true' style={{position:'fixed',inset:0,zIndex:9999,background:'rgba(0,0,0,.55)',display:'flex',alignItems:'center',justifyContent:'center',padding:20}}><div className='module-card' style={{width:'min(460px,100%)',background:'#fff'}}><h3>Customer Payment</h3><p><strong>{displayNo(paymentFor)}</strong> · {paymentFor.customer_name||'Customer'}</p><div style={{textAlign:'center',padding:'10px 0'}}><strong>Customer scans this QR and pays Unique Market</strong><p className='muted' style={{margin:'4px 0 10px'}}>UPI: {upiId}</p><img src={paymentSettings?.qr_image_url||qrUrl} alt='Unique Market UPI QR' style={{width:220,height:220,objectFit:'contain',border:'1px solid #ddd',borderRadius:12}}/><p className='muted' style={{margin:'8px 0'}}>After successful payment, enter the UTR / reference number below.</p></div><label>Payment Amount<input type='number' min='1' value={payment.amount} onChange={e=>setPayment({...payment,amount:e.target.value})} placeholder='Enter amount paid by customer'/></label><label>Customer UPI Transaction / UTR<input required value={payment.reference_no} onChange={e=>setPayment({...payment,reference_no:e.target.value})} placeholder='Enter UTR / reference number'/></label><label>Notes (optional)<textarea value={payment.notes} onChange={e=>setPayment({...payment,notes:e.target.value})} placeholder='Payment notes'/></label>{paymentStatus&&<p className={paymentStatus.includes('successfully')?'muted':'error'}>{paymentStatus}</p>}<div style={{display:'flex',gap:8,marginTop:12}}><button type='button' onClick={collectPayment} disabled={!payment.amount||!payment.reference_no.trim()}>Submit UTR for Verification</button><button type='button' className='secondary' onClick={()=>{if(paymentStatus.includes('Waiting'))return;setPaymentFor(null);setMessage('')}}>Cancel</button></div></div></div>}
 </section>}
