import {useEffect,useMemo,useState} from 'react'
import {supabase} from '../lib/supabase'

const FALLBACK_UPI='sohammane855-8@okhdfcbank'

export default function TechnicianPayment({profile,onBack}){
 const [customers,setCustomers]=useState([]),[customerId,setCustomerId]=useState(''),[challans,setChallans]=useState([]),[challanId,setChallanId]=useState(''),[amount,setAmount]=useState(''),[referenceNo,setReferenceNo]=useState(''),[notes,setNotes]=useState(''),[settings,setSettings]=useState(null),[saving,setSaving]=useState(false),[message,setMessage]=useState(''),[mode,setMode]=useState('Online')
 useEffect(()=>{(async()=>{const[{data:cs},{data:ps}]=await Promise.all([supabase.from('customers').select('id,name,mobile').order('name').limit(500),supabase.from('payment_settings').select('upi_id,account_name,qr_image_url,is_enabled').limit(1).maybeSingle()]);setCustomers(cs||[]);setSettings(ps||null)})()},[])
 useEffect(()=>{(async()=>{setChallanId('');setChallans([]);if(!customerId)return;const{data,error}=await supabase.from('challans').select('id,challan_no,challan_date,subtotal,paid_amount,payment_status,status').eq('customer_id',customerId).order('challan_date',{ascending:false}).order('created_at',{ascending:false}).limit(100);if(!error)setChallans(data||[]);else setMessage(error.message)})()},[customerId])
 const upiId=settings?.upi_id||FALLBACK_UPI,accountName=settings?.account_name||'Unique Market'
 const qrUrl=useMemo(()=>`https://api.qrserver.com/v1/create-qr-code/?size=280x280&data=${encodeURIComponent(`upi://pay?pa=${encodeURIComponent(upiId)}&pn=${encodeURIComponent(accountName)}&cu=INR`)}`,[upiId,accountName])
 async function submit(e){e.preventDefault();setMessage('');if(!customerId||!challanId||!amount||Number(amount)<=0)return setMessage('Select customer, Challan / Call ID and enter a valid amount.');if(mode==='Online'&&!referenceNo.trim())return setMessage('Customer UTR / reference number is required for online payment.');setSaving(true);const payload={customer_id:customerId,challan_id:challanId,payment_date:new Date().toISOString().slice(0,10),amount:Number(amount),mode:mode==='Online'?'UPI':'Cash',status:mode==='Online'?'pending':'confirmed',source:'technician',recorded_by:profile.id,reference_no:mode==='Online'?referenceNo.trim():null,notes:notes.trim()||(mode==='Online'?'Customer QR payment — verification pending':'Cash collected by technician')};const{error}=await supabase.from('payments').insert(payload);setSaving(false);if(error){setMessage(error.message);return}setMessage(mode==='Online'?'UTR submitted. Payment is Verification Pending. Call ID is linked to the Challan No.':'Cash payment recorded successfully with the selected Call ID.');setAmount('');setReferenceNo('');setNotes('')}
 return <section className='role-dashboard'><button className='secondary' type='button' onClick={onBack}>← Dashboard</button><div className='admin-panel'><div className='panel-heading'><div><span className='badge'>TECHNICIAN • CUSTOMER PAYMENT</span><h2>Collect Customer Payment</h2><p>Select the Challan / Call ID against which this payment is collected.</p></div></div>{message&&<p className={message.includes('successfully')||message.startsWith('UTR submitted')?'muted':'error'}>{message}</p>}<form className='admin-form' onSubmit={submit}><label>Customer<select value={customerId} onChange={e=>setCustomerId(e.target.value)}><option value=''>Select customer</option>{customers.map(c=><option key={c.id} value={c.id}>{c.name}{c.mobile?' • '+c.mobile:''}</option>)}</select></label><label>Call ID / Challan No.<select value={challanId} onChange={e=>setChallanId(e.target.value)} disabled={!customerId}><option value=''>{customerId?(challans.length?'Select Challan / Call ID':'No challan found for this customer'):'Select customer first'}</option>{challans.map(c=><option key={c.id} value={c.id}>{c.challan_no}{c.challan_date?' • '+c.challan_date:''}</option>)}</select></label>{mode==='Online'&&<div style={{textAlign:'center',padding:'10px 0 16px'}}><strong>Scan & Pay to Unique Market</strong><p className='muted' style={{margin:'5px 0'}}>UPI: {upiId}</p><img src={settings?.qr_image_url||qrUrl} alt='Unique Market UPI QR' style={{width:220,height:220,objectFit:'contain',border:'1px solid #ddd',borderRadius:12}}/><p className='muted' style={{margin:'8px 0 0'}}>After customer payment, enter the UTR below.</p></div>}<label>Payment Mode<select value={mode} onChange={e=>{setMode(e.target.value);setReferenceNo('')}}><option value='Online'>Online / UPI</option><option value='Cash'>Cash</option></select></label><label>Payment Amount<input type='number' min='1' step='0.01' value={amount} onChange={e=>setAmount(e.target.value)} placeholder='₹ Amount paid by customer'/></label>{mode==='Online'&&<label>Customer UTR / Reference No.<input required value={referenceNo} onChange={e=>setReferenceNo(e.target.value)} placeholder='Enter UTR / transaction reference'/></label>}{mode==='Cash'&&<p className='muted' style={{margin:'-4px 0 8px'}}>Cash received from customer and recorded as confirmed cash collection.</p>}<label>Notes (optional)<input value={notes} onChange={e=>setNotes(e.target.value)} placeholder='Optional payment notes'/></label><button disabled={saving||!customerId||!challanId||!amount||(mode==='Online'&&!referenceNo.trim())}>{saving?'Saving…':mode==='Online'?'Submit UTR for Verification':'Record Cash Payment'}</button></form></div></section>
}
