import {useEffect,useState} from 'react'
import {supabase} from '../lib/supabase'

export default function TechnicianAdmin({onBack}){
 const [rows,setRows]=useState([]),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[message,setMessage]=useState(''),[editing,setEditing]=useState(null),[form,setForm]=useState({name:'',mobile:'',aadhaar_no:'',status:'Active'})
 async function load(){setLoading(true);const {data,error}=await supabase.from('technicians').select('*').order('created_at',{ascending:false}).limit(500);if(error)setMessage(error.message);else setRows(data||[]);setLoading(false)}
 useEffect(()=>{load()},[])
 function add(){setEditing('new');setMessage('');setForm({name:'',mobile:'',aadhaar_no:'',status:'Active'})}
 function edit(r){setEditing(r.id);setMessage('');setForm({name:r.name||'',mobile:r.mobile||'',aadhaar_no:r.aadhaar_no||'',status:r.status||'Active'})}
 async function save(e){e.preventDefault();setMessage('');const name=form.name.trim(),mobile=form.mobile.trim(),aadhaar=form.aadhaar_no.replace(/\D/g,'');if(!name){setMessage('Technician name is required');return}if(!mobile){setMessage('Mobile number is required');return}if(!/^\d{12}$/.test(aadhaar)){setMessage('Aadhaar Number must be exactly 12 digits');return}setSaving(true);const payload={name,mobile,aadhaar_no:aadhaar,status:form.status||'Active'};const q=editing==='new'?supabase.from('technicians').insert(payload).select('*').single():supabase.from('technicians').update(payload).eq('id',editing).select('*').single();const {error}=await q;if(error)setMessage(error.message);else{setMessage('Technician saved successfully');setEditing(null);await load()}setSaving(false)}
 async function remove(id){if(!confirm('Delete this technician? This cannot be undone.'))return;const {error}=await supabase.from('technicians').delete().eq('id',id);if(error)setMessage(error.message);else load()}
 return <section className='admin-panel'><div className='panel-heading'><div><span className='badge'>ADMIN • LIVE</span><h2>Technicians</h2><p>Manage technician records and identity details.</p></div><button className='secondary' type='button' onClick={onBack}>← Dashboard</button></div>{message&&<p className={message.includes('successfully')?'muted':'error'}>{message}</p>}<div className='admin-actions'><button type='button' onClick={add}>＋ Add Technician</button><button type='button' className='secondary' onClick={load}>↻ Refresh</button></div>{editing!==null&&<form className='admin-form' onSubmit={save}><label>Technician Name<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Mobile Number<input required inputMode='numeric' value={form.mobile} onChange={e=>setForm({...form,mobile:e.target.value.replace(/\D/g,'').slice(0,10)})}/></label><label>Aadhaar Number<input required inputMode='numeric' maxLength={12} minLength={12} placeholder='12 digit Aadhaar Number' value={form.aadhaar_no} onChange={e=>setForm({...form,aadhaar_no:e.target.value.replace(/\D/g,'').slice(0,12)})}/></label><label>Status<select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option>Active</option><option>Inactive</option></select></label><button type='submit' disabled={saving}>{saving?'Saving…':'Save Technician'}</button><button type='button' className='secondary' onClick={()=>setEditing(null)}>Cancel</button></form>}{loading?<p className='muted'>Loading technicians…</p>:<div className='data-list'>{rows.map(r=><article key={r.id}><strong>{r.name||'Technician'}</strong><span>{r.mobile||'—'} • Aadhaar: {r.aadhaar_no?`XXXX XXXX ${r.aadhaar_no.slice(-4)}`:'Not available'} • {r.status||'Active'}</span><div><button type='button' className='secondary' onClick={()=>edit(r)}>Edit</button><button type='button' className='secondary' onClick={()=>remove(r.id)}>Delete</button></div></article>)}{!rows.length&&<p className='muted'>No technicians found.</p>}</div>}</section>
}