import {useEffect,useState} from 'react'
import {supabase} from '../lib/supabase'

export default function TechnicianRequest({profile,onBack}){
 const[rows,setRows]=useState([]),[form,setForm]=useState({title:'',description:'',priority:'normal'}),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[message,setMessage]=useState('')
 async function load(){if(!profile?.id)return;setLoading(true);const{data,error}=await supabase.from('technician_requests').select('id,title,description,priority,status,created_at,updated_at').eq('technician_id',profile.id).order('created_at',{ascending:false});if(error)setMessage(error.message);else setRows(data||[]);setLoading(false)}
 useEffect(()=>{load()},[profile?.id])
 async function submit(e){e.preventDefault();if(!form.title.trim()||!form.description.trim())return setMessage('Title and description are required.');setSaving(true);setMessage('');const{error}=await supabase.from('technician_requests').insert({technician_id:profile.id,title:form.title.trim(),description:form.description.trim(),priority:form.priority});if(error)setMessage(error.message);else{setForm({title:'',description:'',priority:'normal'});setMessage('Request sent to Admin successfully.');load()}setSaving(false)}
 return <section className='admin-panel'><div className='panel-heading'><div><span className='badge'>TECHNICIAN • SUPPORT</span><h2>Raise Request</h2><p>Send an internal service or support request to Admin.</p></div><button className='secondary' type='button' onClick={onBack}>← Dashboard</button></div>{message&&<p className={message.includes('successfully')?'muted':'error'}>{message}</p>}<form className='admin-form' onSubmit={submit}><label>Request Title<input value={form.title} onChange={e=>setForm({...form,title:e.target.value})} placeholder='e.g. Material required for site' required/></label><label>Priority<select value={form.priority} onChange={e=>setForm({...form,priority:e.target.value})}><option value='low'>Low</option><option value='normal'>Normal</option><option value='high'>High</option><option value='urgent'>Urgent</option></select></label><label>Description<textarea rows='5' value={form.description} onChange={e=>setForm({...form,description:e.target.value})} placeholder='Describe what you need from Admin' required/></label><button type='submit' disabled={saving}>{saving?'Sending…':'Send Request'}</button></form><div className='admin-form' style={{marginTop:16}}><div className='panel-heading'><div><h3>My Requests</h3><p className='muted'>Track requests raised by you.</p></div><button className='secondary' type='button' onClick={load}>Refresh</button></div>{loading?<p>Loading…</p>:rows.length===0?<p className='muted'>No requests yet.</p>:<div className='data-list'>{rows.map(r=><article key={r.id}><strong>{r.title}</strong><span>{String(r.status||'open').toUpperCase()} · {String(r.priority||'normal').toUpperCase()}<small>{r.description} · {new Date(r.created_at).toLocaleString('en-IN')}</small></span></article>)}</div>}</div></section>
}