import { useEffect, useState } from 'react'
import { supabase } from '../lib/supabase'
import { subscribeToComplaints } from '../lib/realtime'
const statusLabel={open:'NEW REQUEST',assigned:'ASSIGNED',in_progress:'IN PROGRESS',resolved:'SERVICE COMPLETED',closed:'CLOSED'}
export default function TechnicianModule({profile,mode='assigned',onBack}){
 const[items,setItems]=useState([]),[query,setQuery]=useState(''),[searchType,setSearchType]=useState('name'),[fromDate,setFromDate]=useState(''),[toDate,setToDate]=useState(''),[loading,setLoading]=useState(true),[message,setMessage]=useState(''),[paymentFor,setPaymentFor]=useState(null),[payment,setPayment]=useState({amount:'',mode:'Cash',reference_no:'',notes:''})
 const[cashToday,setCashToday]=useState(0),[upiToday,setUpiToday]=useState(0),[totalToday,setTotalToday]=useState(0),[todayPayments,setTodayPayments]=useState([])
 async function loadPaymentsToday(){if(!supabase||!profile?.id)return;const today=new Date().toISOString().slice(0,10);const{data,error}=await supabase.from('payments').select('id,customer_id,amount,mode,reference_no,status,payment_date,created_at,notes,recorded_by,source').eq('payment_date',today).eq('status','confirmed').eq('recorded_by',profile.id).order('created_at',{ascending:false}).limit(200);if(error){setMessage(error.message);return}const rows=data||[];setCashToday(rows.filter(p=>String(p.mode||'').toUpperCase()==='CASH').reduce((s,p)=>s+Number(p.amount||0),0));setUpiToday(rows.filter(p=>String(p.mode||'').toUpperCase()==='UPI').reduce((s,p)=>s+Number(p.amount||0),0));setTotalToday(rows.reduce((s,p)=>s+Number(p.amount||0),0));setTodayPayments(rows)}
 async function load(search=query,type=searchType,from=fromDate,to=toDate){if(!supabase||!profile?.id)return;setLoading(true);setMessage('');let q=supabase.from('complaints').select('id,complaint_no,ticket_no,title,description,category,priority,status,location_text,address,created_at,customer_name,customer_phone,company_name,technician_id,customer_id,started_at,completed_at,resolution_notes,assigned_at').eq('technician_id',profile.id).order('created_at',{ascending:false});if(mode==='today'){const today=new Date().toISOString().slice(0,10);q=q.or(`created_at.gte.${today}T00:00:00,assigned_at.gte.${today}T00:00:00,started_at.gte.${today}T00:00:00`);await loadPaymentsToday()}else if(mode==='find'){if(type==='name'&&search.trim())q=q.ilike('customer_name',`%${search.trim()}%`);if(type==='code'&&search.trim())q=q.or(`complaint_no.ilike.%${search.trim()}%,ticket_no.ilike.%${search.trim()}%`);if(type==='date'&&from)q=q.gte('created_at',`${from}T00:00:00`).lte('created_at',`${to||from}T23:59:59`)}const{data,error}=await q;if(error)setMessage(error.message);else setItems(data||[]);setLoading(false)}
 useEffect(()=>{if(!profile?.id)return;load('',searchType,fromDate,toDate);const unsubscribe=subscribeToComplaints(()=>load());return unsubscribe},[profile?.id,mode])
 async function setStatus(item,status,extra={}){setMessage('');const{error}=await supabase.from('complaints').update({status,updated_at:new Date().toISOString(),...extra}).eq('id',item.id).eq('technician_id',profile.id);if(error)setMessage(error.message);else load()}
 async function claimJob(item){const{error}=await supabase.from('complaints').update({technician_id:profile.id,status:'assigned',assigned_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('id',item.id).is('technician_id',null).eq('status','open');if(error)setMessage(error.message);else load()}
 async function acceptJob(item){await setStatus(item,'in_progress',{started_at:new Date().toISOString()})}
 async function completeService(item){const notes=window.prompt('Service completion notes (optional):',item.resolution_notes||'');if(notes===null)return;await setStatus(item,'resolved',{completed_at:new Date().toISOString(),resolution_notes:notes})}
 async function collectPayment(){if(!paymentFor)return;const amount=Number(payment.amount);if(!amount||amount<=0)return setMessage('Enter a valid payment amount.');if(payment.mode==='UPI'&&!payment.reference_no.trim())return setMessage('UPI reference number is required.');let customerProfileId=null;if(paymentFor.customer_id){const{data:customer,error:customerError}=await supabase.from('customers').select('profile_id,user_id').eq('id',paymentFor.customer_id).maybeSingle();if(customerError)return setMessage(customerError.message);customerProfileId=customer?.profile_id||customer?.user_id}if(!customerProfileId){const{data:complaint,error:complaintError}=await supabase.from('complaints').select('customer_id').eq('id',paymentFor.id).maybeSingle();if(complaintError)return setMessage(complaintError.message);customerProfileId=complaint?.customer_id}if(!customerProfileId)return setMessage('Customer profile could not be linked for payment.');const{data:profileRow,error:profileError}=await supabase.from('profiles').select('id').eq('id',customerProfileId).maybeSingle();if(profileError)return setMessage(profileError.message);if(!profileRow?.id)return setMessage('Customer profile does not exist.');const{error}=await supabase.from('payments').insert({customer_id:profileRow.id,amount,mode:payment.mode,reference_no:payment.reference_no.trim()||null,notes:`Service payment for ${paymentFor.complaint_no||paymentFor.id}${payment.notes.trim()?` — ${payment.notes.trim()}`:''}`,recorded_by:profile.id,status:'confirmed',source:'technician',payment_date:new Date().toISOString().slice(0,10)});if(error)return setMessage(error.message);const{error:closeError}=await supabase.from('complaints').update({status:'closed',updated_at:new Date().toISOString()}).eq('id',paymentFor.id).eq('technician_id',profile.id);if(closeError)return setMessage(closeError.message);setPaymentFor(null);setPayment({amount:'',mode:'Cash',reference_no:'',notes:''});setMessage('Payment collected and service file closed successfully.');await loadPaymentsToday();load()}
 const displayNo=i=>i.complaint_no||i.ticket_no||`C/NO-${i.id}`
 return <section className='complaints-panel'><div className='panel-heading'><div><span className='badge'>TECHNICIAN DESK</span><h2>{mode==='find'?'Find Complaint':mode==='today'?"Today's Visits":'Live Service Requests'}</h2><p>{mode==='find'?'Search only by Party / Customer Name, Complaint Code or Date-wise.':mode==='today'?"Today's assigned visits and collection summary.":'Customer-raised open requests and complaints assigned to you.'}</p></div><div><span className='status'>LIVE</span> <button className='secondary' type='button' onClick={onBack}>← Back</button></div></div>
 {mode==='today'&&<div className='admin-stats' style={{margin:'18px 0'}}><div className='stat-card'><strong>₹{cashToday.toLocaleString('en-IN')}</strong><span>Cash Collected Today</span></div><div className='stat-card'><strong>₹{upiToday.toLocaleString('en-IN')}</strong><span>Company QR / UPI Today</span></div><div className='stat-card'><strong>₹{totalToday.toLocaleString('en-IN')}</strong><span>Total Collected Today</span></div></div>}
 {mode==='find'&&<form className='search-row' onSubmit={e=>{e.preventDefault();load(query,searchType,fromDate,toDate)}} style={{display:'flex',gap:8,margin:'18px 0',flexWrap:'wrap'}}><select value={searchType} onChange={e=>{setSearchType(e.target.value);setQuery('');setFromDate('');setToDate('');setItems([])}}><option value='name'>Party / Customer Name</option><option value='code'>Complaint Code</option><option value='date'>Date-wise Search</option></select>{searchType==='date'?<><input type='date' value={fromDate} onChange={e=>setFromDate(e.target.value)}/><input type='date' value={toDate} onChange={e=>setToDate(e.target.value)}/></>:<input value={query} onChange={e=>setQuery(e.target.value)} placeholder={searchType==='name'?'Enter Party / Customer Name':'Enter Complaint Code'}/>}<button type='submit'>Find Complaint</button></form>}
 {message&&<p className={message.includes('successfully')?'muted':'error'}>{message}</p>}
 {mode==='today'&&todayPayments.length>0&&<div className='module-card' style={{marginBottom:18}}><h3>Today's Payment History</h3>{todayPayments.map(p=><p key={p.id}>₹{Number(p.amount||0).toLocaleString('en-IN')} · {p.mode||'—'} · {p.reference_no||'—'}</p>)}</div>}
 {loading?<p>Loading…</p>:items.length===0?<div className='module-card'><h3>No visits found</h3></div>:<div className='modules'>{items.map(item=><article className='module-card' key={item.id}><span className='status'>{displayNo(item)} · {statusLabel[item.status]||'OPEN'}</span><h3>{item.title||item.description||'Service Complaint'}</h3><p><strong>Customer:</strong> {item.customer_name||'—'} · {item.customer_phone||'—'}</p><p><strong>Company:</strong> {item.company_name||'—'}</p><p><strong>Address:</strong> {item.location_text||item.address||'—'}</p><p>{item.description||'No additional description.'}</p><div style={{display:'flex',gap:8,flexWrap:'wrap',marginTop:12}}>{item.status==='open'&&!item.technician_id&&<button type='button' onClick={()=>claimJob(item)}>✓ Accept Request</button>}{item.status==='assigned'&&item.technician_id===profile.id&&<button type='button' onClick={()=>acceptJob(item)}>✓ Start Service</button>}{item.status==='in_progress'&&item.technician_id===profile.id&&<button type='button' onClick={()=>completeService(item)}>✓ Service Completed</button>}{item.status==='resolved'&&item.technician_id===profile.id&&<button type='button' onClick={()=>{setPaymentFor(item);setMessage('')}}>💳 Collect Cash / UPI & Close</button>}{item.status==='closed'&&<strong>✓ Service File Closed</strong>}</div></article>)}</div>}
 {paymentFor&&<div role='dialog' aria-modal='true' style={{position:'fixed',inset:0,zIndex:9999,background:'rgba(0,0,0,.55)',display:'flex',alignItems:'center',justifyContent:'center',padding:20}}><div className='module-card' style={{width:'min(460px,100%)',background:'#fff'}}><h3>Collect Cash / UPI</h3><p><strong>{displayNo(paymentFor)}</strong> · {paymentFor.customer_name||'Customer'}</p><label>Payment Mode<select value={payment.mode} onChange={e=>setPayment({...payment,mode:e.target.value,reference_no:e.target.value==='Cash'?'':payment.reference_no})}><option value='Cash'>Cash</option><option value='UPI'>Company QR / UPI</option></select></label><label>Amount<input type='number' min='1' value={payment.amount} onChange={e=>setPayment({...payment,amount:e.target.value})} placeholder='Enter amount'/></label>{payment.mode==='UPI'&&<label>UPI Reference / UTR<input value={payment.reference_no} onChange={e=>setPayment({...payment,reference_no:e.target.value})} placeholder='Enter UTR / reference'/></label>}<label>Notes (optional)<textarea value={payment.notes} onChange={e=>setPayment({...payment,notes:e.target.value})} placeholder='Payment notes'/></label><div style={{display:'flex',gap:8,marginTop:12}}><button type='button' onClick={collectPayment}>✓ Confirm Payment & Close</button><button type='button' className='secondary' onClick={()=>{setPaymentFor(null);setMessage('')}}>Cancel</button></div></div></div>}
 </section>}
