-- Retire legacy pending WhatsApp rows created before the unified outbox.
-- New events are generated by the complaint/payment triggers and can be
-- safely processed across bot restarts.
update public.whatsapp_notification_events
set status = 'failed',
    error_message = coalesce(error_message, 'Legacy pending event retired during WhatsApp outbox migration')
where status = 'pending'
  and created_at < now();

