create table if not exists public.payment_settings (id uuid primary key default gen_random_uuid(), upi_id text, account_name text, qr_image_url text, is_enabled boolean not null default true, updated_at timestamptz not null default now(), updated_by uuid references public.profiles(id) on delete set null);
alter table public.payments add column if not exists recorded_by uuid references public.profiles(id) on delete set null;
alter table public.payments add column if not exists status text not null default 'confirmed';
alter table public.payments add column if not exists source text not null default 'admin';
alter table public.payments drop constraint if exists payments_mode_check;
alter table public.payments add constraint payments_mode_check check (mode is null or mode in ('Cash','UPI'));
alter table public.payments drop constraint if exists payments_status_check;
alter table public.payments add constraint payments_status_check check (status in ('pending','confirmed','rejected'));
alter table public.payments drop constraint if exists payments_source_check;
alter table public.payments add constraint payments_source_check check (source in ('customer','technician','admin'));
alter table public.payment_settings enable row level security;
drop policy if exists payment_settings_admin_all on public.payment_settings;
create policy payment_settings_admin_all on public.payment_settings for all to authenticated using (public.is_admin()) with check (public.is_admin());
drop policy if exists payment_settings_customer_read on public.payment_settings;
create policy payment_settings_customer_read on public.payment_settings for select to authenticated using (true);
drop policy if exists payments_admin_all on public.payments;
create policy payments_admin_all on public.payments for all to authenticated using (public.is_admin()) with check (public.is_admin());
drop policy if exists payments_customer_select on public.payments;
create policy payments_customer_select on public.payments for select to authenticated using (customer_id = auth.uid());
drop policy if exists payments_customer_insert_upi on public.payments;
create policy payments_customer_insert_upi on public.payments for insert to authenticated with check (customer_id = auth.uid() and mode = 'UPI' and status = 'pending' and source = 'customer');
drop policy if exists payments_technician_insert_cash on public.payments;
create policy payments_technician_insert_cash on public.payments for insert to authenticated with check (recorded_by = auth.uid() and mode = 'Cash' and status = 'confirmed' and source = 'technician' and exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'technician'));
insert into public.payment_settings (upi_id,account_name,is_enabled) select null,null,true where not exists (select 1 from public.payment_settings);